import type { ResearchEntry } from "./research";

// Primary PubMed records checked 2026-10-04; notes are original paraphrases.
export const topicResearchEntries: ResearchEntry[] = [
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Intestinal adaptation after bowel resection",
    "evidence": "preclinical",
    "model": "Rats after extensive small-bowel resection",
    "focus": "Intestinal adaptation after bowel resection",
    "title": "Gastric pentadecapeptide BPC 157 and short bowel syndrome in rats.",
    "finding": "Treated rats gained weight and showed changes in intestinal structure and greater anastomosis breaking strength during four weeks of follow-up.",
    "limitation": "Surgically induced short bowel in rats does not establish treatment outcomes or nutritional recovery in people.",
    "authors": "Sever M et al.",
    "journal": "Digestive diseases and sciences",
    "year": 2009,
    "source": "https://pubmed.ncbi.nlm.nih.gov/19093208/",
    "sourceId": "PMID 19093208"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Healing in an esophageal fistula model",
    "evidence": "preclinical",
    "model": "Rats with surgically established esophagocutaneous fistulas",
    "focus": "Healing in an esophageal fistula model",
    "title": "Pentadecapeptide BPC 157 and the esophagocutaneous fistula healing therapy.",
    "finding": "The authors observed less leakage and faster defect closure, together with changes in nitric-oxide-related gene expression and sphincter pressure.",
    "limitation": "Four-day outcomes in surgically injured rats cannot establish clinical fistula treatment or long-term safety.",
    "authors": "Cesarec V et al.",
    "journal": "European journal of pharmacology",
    "year": 2013,
    "source": "https://pubmed.ncbi.nlm.nih.gov/23220707/",
    "sourceId": "PMID 23220707"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Acute and chronic gastric ulcer models",
    "evidence": "preclinical",
    "model": "Rats with experimentally induced gastric ulcers",
    "focus": "Acute and chronic gastric ulcer models",
    "title": "Protective effects of pentadecapeptide BPC 157 on gastric ulcer in rats.",
    "finding": "BPC-157 reduced ulcer area in several injury models and increased epithelial rebuilding and granulation tissue in the chronic-ulcer experiment.",
    "limitation": "Despite references to human ulcers in the abstract, the reported experiments were in rats. Their results do not establish human ulcer healing.",
    "authors": "Xue XC et al.",
    "journal": "World journal of gastroenterology",
    "year": 2004,
    "source": "https://pubmed.ncbi.nlm.nih.gov/15052688/",
    "sourceId": "PMID 15052688"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Burn repair under corticosteroid exposure",
    "evidence": "preclinical",
    "model": "Burned mice receiving corticosteroids and topical creams",
    "focus": "Burn repair under corticosteroid exposure",
    "title": "Corticosteroid-impairment of healing and gastric pentadecapeptide BPC-157 creams in burned mice.",
    "finding": "The authors reported improved microscopic and mechanical healing measures with BPC-157 cream, including in corticosteroid-exposed animals. Gastric lesions and splenic-cell responses were also examined.",
    "limitation": "Mouse burns, a topical preparation, and concurrent corticosteroids are a specific experimental setting. Findings do not establish clinical burn care or effects through other routes.",
    "authors": "Sikiric P et al.",
    "journal": "Burns : journal of the International Society for Burn Injuries",
    "year": 2003,
    "source": "https://pubmed.ncbi.nlm.nih.gov/12781609/",
    "sourceId": "PMID 12781609"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Early outcomes after experimental brain injury",
    "evidence": "preclinical",
    "model": "Mice with weight-drop traumatic brain injury",
    "focus": "Early outcomes after experimental brain injury",
    "title": "Traumatic brain injury in mice and pentadecapeptide BPC 157 effect.",
    "finding": "The authors reported less severe brain lesions and edema and changes in consciousness and mortality during the first 24 hours after injury.",
    "limitation": "Much of the experiment involved treatment before injury. Brief mouse follow-up cannot establish human concussion recovery, neurological benefit, or long-term safety.",
    "authors": "Tudor M et al.",
    "journal": "Regulatory peptides",
    "year": 2010,
    "source": "https://pubmed.ncbi.nlm.nih.gov/19931318/",
    "sourceId": "PMID 19931318"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Repair at the muscle–tendon junction",
    "evidence": "preclinical",
    "model": "Rats after surgical quadriceps muscle–tendon separation",
    "focus": "Repair at the muscle–tendon junction",
    "title": "Stable Gastric Pentadecapeptide BPC 157 as a Therapy for the Disable Myotendinous Junctions in Rats.",
    "finding": "Treated animals showed smaller defects, improved functional and mechanical measures, and less muscle atrophy. Histology and inflammatory and oxidative-stress markers were assessed through 42 days.",
    "limitation": "A deliberately separated rat muscle–tendon junction is not a human sports injury. These results do not establish clinical recovery or safety.",
    "authors": "Japjec M et al.",
    "journal": "Biomedicines",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/34829776/",
    "sourceId": "PMID 34829776"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Contractile responses in isolated heart tissue",
    "evidence": "preclinical",
    "model": "Isolated right atrial tissue from cardiac-surgery patients",
    "focus": "Contractile responses in isolated heart tissue",
    "title": "Inotropic effects of retatrutide in isolated human atrial preparations.",
    "finding": "Retatrutide increased contraction strength in isolated atrial preparations. Receptor-blocking experiments implicated its target receptors and cAMP-associated signaling.",
    "limitation": "Patient-derived tissue outside the body remains laboratory evidence. This does not establish cardiac benefit, arrhythmia risk, or clinical safety in people.",
    "authors": "Neumann J et al.",
    "journal": "Naunyn-Schmiedeberg's archives of pharmacology",
    "year": 2026,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40613938/",
    "sourceId": "PMID 40613938",
    "studyType": "laboratory"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Alcohol-related cues in a rat experiment",
    "evidence": "preclinical",
    "model": "Male and female rats in operant alcohol-discrimination experiments",
    "focus": "Alcohol-related cues in a rat experiment",
    "title": "Semaglutide, tirzepatide, and retatrutide attenuate the interoceptive effects of alcohol in male and female rats.",
    "finding": "Acute retatrutide, tirzepatide, and semaglutide reduced alcohol discrimination. Repeated-treatment findings in this paper concerned semaglutide rather than retatrutide.",
    "limitation": "A rat discrimination task does not establish reduced drinking or treatment of alcohol use disorder in humans. The three drugs should not be treated as interchangeable.",
    "authors": "Windram M et al.",
    "journal": "Psychopharmacology",
    "year": 2026,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40699363/",
    "sourceId": "PMID 40699363"
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Neuronal changes in Alzheimer disease models",
    "evidence": "preclinical",
    "model": "Human stem-cell-derived brain organoids and 5xfAD mice",
    "focus": "Neuronal changes in Alzheimer disease models",
    "title": "Thymosin beta 4 as an Alzheimer disease intervention target identified using human brain organoids.",
    "finding": "Full-length thymosin beta4 treatment improved neuronal-development measures and reduced amyloid-related abnormalities in familial-disease organoids. The authors also reported effects in a mouse disease model.",
    "limitation": "Human organoids are laboratory models, not treated patients. This paper studies thymosin beta4 and does not establish TB-500 equivalence or Alzheimer disease treatment in people.",
    "authors": "Zeng PM et al.",
    "journal": "Stem cell reports",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40816274/",
    "sourceId": "PMID 40816274",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Liver injury and fibrosis in rodent models",
    "evidence": "preclinical",
    "model": "Mice and rats exposed to carbon tetrachloride",
    "focus": "Liver injury and fibrosis in rodent models",
    "title": "Effects of exogenous thymosin β4 on carbon tetrachloride-induced liver injury and fibrosis.",
    "finding": "Thymosin beta4 attenuated liver-enzyme changes, tissue injury, collagen accumulation, and several inflammatory and oxidative-stress markers after chemical exposure.",
    "limitation": "Chemical rodent injury does not establish effects on human liver disease. Full-length thymosin beta4 results cannot be assigned to a product labeled TB-500 without verifying equivalence.",
    "authors": "Li X et al.",
    "journal": "Scientific reports",
    "year": 2017,
    "source": "https://pubmed.ncbi.nlm.nih.gov/28724974/",
    "sourceId": "PMID 28724974",
    "related": true
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Plaque inflammation and vascular function",
    "evidence": "preclinical",
    "model": "Atherosclerotic mice on a high-fat diet",
    "focus": "Plaque inflammation and vascular function",
    "title": "Pharmacological activation of the melanocortin system limits plaque inflammation and ameliorates vascular dysfunction in atherosclerotic mice.",
    "finding": "Melanotan II reduced plaque glucose-tracer uptake and inflammatory markers and improved aortic relaxation measures. Plaque size, macrophage accumulation, and cholesterol were not reduced.",
    "limitation": "Changes in mouse inflammation and ex vivo vascular function do not establish clinical cardiovascular benefit or tanning safety.",
    "authors": "Rinne P et al.",
    "journal": "Arteriosclerosis, thrombosis, and vascular biology",
    "year": 2014,
    "source": "https://pubmed.ncbi.nlm.nih.gov/24790139/",
    "sourceId": "PMID 24790139"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "A report of priapism after Melanotan II",
    "evidence": "human",
    "model": "One patient after self-reported subcutaneous use",
    "focus": "A report of priapism after Melanotan II",
    "title": "Melanotan Tanning Injection: A Rare Cause of Priapism.",
    "finding": "The patient developed acute ischemic priapism after Melanotan II use and required surgical management after initial measures failed.",
    "limitation": "One case can identify a possible adverse event but cannot determine its frequency or prove causation. Product identity and exposure are not equivalent to a controlled trial.",
    "authors": "Mallory CW et al.",
    "journal": "Sexual medicine",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/33460908/",
    "sourceId": "PMID 33460908",
    "studyType": "case-report"
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Bone erosion in a particle-induced model",
    "evidence": "preclinical",
    "model": "Mouse skull osteolysis model and bone-cell cultures",
    "focus": "Bone erosion in a particle-induced model",
    "title": "MOTS-c inhibits Osteolysis in the Mouse Calvaria by affecting osteocyte-osteoclast crosstalk and inhibiting inflammation.",
    "finding": "MOTS-c reduced particle-associated bone erosion and inflammation. Cell experiments linked effects to osteocyte signaling, osteoclast formation, and AMPK-associated inflammatory pathways.",
    "limitation": "Particle-induced mouse osteolysis and cultured cells do not establish human bone repair, implant outcomes, or administration safety.",
    "authors": "Yan Z et al.",
    "journal": "Pharmacological research",
    "year": 2019,
    "source": "https://pubmed.ncbi.nlm.nih.gov/31369811/",
    "sourceId": "PMID 31369811"
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Fat-tissue responses to cold exposure",
    "evidence": "preclinical",
    "model": "Cold-exposed mice and adipose thermogenesis measurements",
    "focus": "Fat-tissue responses to cold exposure",
    "title": "Mitochondrial-Derived Peptide MOTS-c Increases Adipose Thermogenic Activation to Promote Cold Adaptation.",
    "finding": "MOTS-c treatment improved cold tolerance and altered brown-fat thermogenic genes and white-fat browning. ERK inhibition disrupted some of these responses.",
    "limitation": "Cold-stressed animal findings do not establish human fat loss, exercise performance, or benefit from administering MOTS-c.",
    "authors": "Lu H et al.",
    "journal": "International journal of molecular sciences",
    "year": 2019,
    "source": "https://pubmed.ncbi.nlm.nih.gov/31109005/",
    "sourceId": "PMID 31109005"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Mammary tumors in a transgenic mouse model",
    "evidence": "preclinical",
    "model": "Female HER-2/neu transgenic mice",
    "focus": "Mammary tumors in a transgenic mouse model",
    "title": "Inhibitory effect of the peptide epitalon on the development of spontaneous mammary tumors in HER-2/neu transgenic mice.",
    "finding": "Epitalon reduced cumulative mammary tumor counts and maximum tumor size in this model. Lung metastasis size decreased, but the number of metastases did not.",
    "limitation": "One genetically tumor-prone mouse model cannot establish human cancer prevention, treatment, or long-term safety. Findings differ by endpoint.",
    "authors": "Anisimov VN et al.",
    "journal": "International journal of cancer",
    "year": 2002,
    "source": "https://pubmed.ncbi.nlm.nih.gov/12209581/",
    "sourceId": "PMID 12209581"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Melatonin and cortisol rhythms in older monkeys",
    "evidence": "preclinical",
    "model": "Female rhesus monkeys of different ages",
    "focus": "Melatonin and cortisol rhythms in older monkeys",
    "title": "Regulatory effect of Epithalon on production of melatonin and cortisol in old monkeys.",
    "finding": "The authors reported increased evening melatonin and changes toward normalized cortisol rhythms in older animals after Epithalon exposure.",
    "limitation": "The short abstract provides limited methodological detail. Hormone rhythms in monkeys do not establish improved human sleep, longevity, or clinical benefit.",
    "authors": "Goncharova ND et al.",
    "journal": "Bulletin of experimental biology and medicine",
    "year": 2001,
    "source": "https://pubmed.ncbi.nlm.nih.gov/11550036/",
    "sourceId": "PMID 11550036"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Barrier and inflammation measures in colitis",
    "evidence": "preclinical",
    "model": "DSS-induced colitis in mice and mouse-cell co-cultures",
    "focus": "Barrier and inflammation measures in colitis",
    "title": "Exploring the beneficial effects of GHK-Cu on an experimental model of colitis and the underlying mechanisms.",
    "finding": "GHK-Cu improved measured disease and tissue-injury outcomes and altered tight-junction proteins and inflammatory markers. Cell experiments examined SIRT1/STAT3-associated signaling.",
    "limitation": "Chemically induced mouse colitis and cultured mouse cells do not establish treatment of human inflammatory bowel disease or route-specific safety.",
    "authors": "Mao S et al.",
    "journal": "Frontiers in pharmacology",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40672369/",
    "sourceId": "PMID 40672369"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Ferritin-associated lipid oxidation",
    "evidence": "preclinical",
    "model": "Laboratory ferritin iron-release and lipid-peroxidation assays",
    "focus": "Ferritin-associated lipid oxidation",
    "title": "Effects of glycyl-histidyl-lysyl chelated Cu(II) on ferritin dependent lipid peroxidation.",
    "finding": "GHK-Cu inhibited lipid oxidation when ferritin was the iron source and reduced ferritin iron release. Significant superoxide-dismutase-like or ceruloplasmin-like activity was not observed.",
    "limitation": "A biochemical mechanism proposed from laboratory assays does not establish clinical wound healing or general antioxidant effects in people.",
    "authors": "Miller DM et al.",
    "journal": "Advances in experimental medicine and biology",
    "year": 1990,
    "source": "https://pubmed.ncbi.nlm.nih.gov/2244543/",
    "sourceId": "PMID 2244543",
    "studyType": "laboratory"
  }
];
