import type { ResearchEntry } from "./research";

// Primary citation metadata and abstracts checked against PubMed on 2026-10-04.
// Notes summarize reported outcomes; trial analyses and related compounds are labeled.
export const additionalResearchEntries: ResearchEntry[] = [
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Knee-pain follow-up",
    "evidence": "human",
    "model": "Retrospective records and telephone follow-up",
    "focus": "Knee-pain follow-up",
    "title": "Intra-Articular Injection of BPC 157 for Multiple Types of Knee Pain.",
    "finding": "Respondents reported reduced knee pain after BPC-157 alone or combined with thymosin beta4.",
    "limitation": "Uncontrolled, subjective follow-up cannot establish efficacy. Combined treatment in some patients prevents attribution to BPC-157 alone.",
    "authors": "Lee E et al.",
    "journal": "Alternative therapies in health and medicine",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/34324435/",
    "sourceId": "PMID 34324435",
    "studyType": "observational"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Exploratory safety report",
    "evidence": "human",
    "model": "Uncontrolled intravenous pilot in two previous users",
    "focus": "Exploratory safety report",
    "title": "Safety of Intravenous Infusion of BPC157 in Humans: A Pilot Study.",
    "finding": "The two participants had no reported adverse effects or concerning changes in the measured short-term blood tests and vital signs.",
    "limitation": "Two selected previous users and only three days of follow-up cannot establish safety, detect uncommon harms, or support other routes of administration.",
    "authors": "Lee E et al.",
    "journal": "Alternative therapies in health and medicine",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40131143/",
    "sourceId": "PMID 40131143",
    "studyType": "observational"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Bladder symptom report",
    "evidence": "human",
    "model": "Uncontrolled report in 12 women with interstitial cystitis",
    "focus": "Bladder symptom report",
    "title": "Effect of BPC-157 on Symptoms in Patients with Interstitial Cystitis: A Pilot Study.",
    "finding": "Participants reported symptom improvement after a bladder procedure involving BPC-157, with no adverse events reported in this small series.",
    "limitation": "No randomization or control group; subjective reports cannot isolate a peptide effect or establish long-term safety.",
    "authors": "Lee E et al.",
    "journal": "Alternative therapies in health and medicine",
    "year": 2024,
    "source": "https://pubmed.ncbi.nlm.nih.gov/39325560/",
    "sourceId": "PMID 39325560",
    "studyType": "observational"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Ligament injury",
    "evidence": "preclinical",
    "model": "Transected medial collateral ligament in rats",
    "focus": "Ligament injury",
    "title": "Pentadecapeptide BPC 157 (PL 14736) improves ligament healing in the rat.",
    "finding": "Functional, mechanical, and histological measures of injured ligament recovery improved in treated rats over the observation period.",
    "limitation": "A surgically injured rat ligament does not establish healing or safety in people.",
    "authors": "Cerovecki T et al.",
    "journal": "Journal of orthopaedic research : official publication of the Orthopaedic Research Society",
    "year": 2010,
    "source": "https://pubmed.ncbi.nlm.nih.gov/20225319/",
    "sourceId": "PMID 20225319"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Periodontal inflammation",
    "evidence": "preclinical",
    "model": "Ligature-induced periodontitis in rats",
    "focus": "Periodontal inflammation",
    "title": "Antiinflammatory effect of BPC 157 on experimental periodontitis in rats.",
    "finding": "Treatment reduced measured inflammation, plasma extravasation, and alveolar bone loss in the experimental model.",
    "limitation": "An induced rodent periodontal lesion is not a clinical trial of human gum disease.",
    "authors": "Keremi B et al.",
    "journal": "Journal of physiology and pharmacology : an official journal of the Polish Physiological Society",
    "year": 2009,
    "source": "https://pubmed.ncbi.nlm.nih.gov/20388954/",
    "sourceId": "PMID 20388954"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Peripheral nerve injury",
    "evidence": "preclinical",
    "model": "Transected sciatic nerve in rats",
    "focus": "Peripheral nerve injury",
    "title": "Peptide therapy with pentadecapeptide BPC 157 in traumatic nerve injury.",
    "finding": "The study reported improvements in nerve histology, electrophysiology, and walking measures after experimental nerve repair.",
    "limitation": "Surgical nerve injury in rats does not establish recovery of human neuropathy or nerve injuries.",
    "authors": "Gjurasin M et al.",
    "journal": "Regulatory peptides",
    "year": 2010,
    "source": "https://pubmed.ncbi.nlm.nih.gov/19903499/",
    "sourceId": "PMID 19903499"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Burn wound biology",
    "evidence": "preclinical",
    "model": "Burn injuries in mice",
    "focus": "Burn wound biology",
    "title": "Pentadecapeptide BPC 157 cream improves burn-wound healing and attenuates burn-gastric lesions in mice.",
    "finding": "Topical treatment was associated with improved re-epithelialization and mechanical wound properties in burned mice.",
    "limitation": "Animal wound outcomes cannot establish clinical burn treatment, formulation equivalence, or human safety.",
    "authors": "Mikus D et al.",
    "journal": "Burns : journal of the International Society for Burn Injuries",
    "year": 2001,
    "source": "https://pubmed.ncbi.nlm.nih.gov/11718984/",
    "sourceId": "PMID 11718984"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Muscle injury",
    "evidence": "preclinical",
    "model": "Crushed gastrocnemius muscle in rats",
    "focus": "Muscle injury",
    "title": "Gastric pentadecapeptide BPC 157 as an effective therapy for muscle crush injury in the rat.",
    "finding": "Researchers reported less hematoma, edema, and contracture, alongside improved muscle function and histology.",
    "limitation": "A short experimental rat injury study does not establish human injury recovery.",
    "authors": "Novinscak T et al.",
    "journal": "Surgery today",
    "year": 2008,
    "source": "https://pubmed.ncbi.nlm.nih.gov/18668315/",
    "sourceId": "PMID 18668315"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Experimental pain response",
    "evidence": "preclinical",
    "model": "Paw-incision and formalin tests in rats",
    "focus": "Experimental pain response",
    "title": "The anti-nociceptive effect of BPC-157 on the incisional pain model in rats.",
    "finding": "Treatment increased withdrawal thresholds after incision and reduced the early, but not late, phase of the formalin response.",
    "limitation": "Brief experimental pain responses do not demonstrate durable clinical analgesia or treatment safety.",
    "authors": "Jung YH et al.",
    "journal": "Journal of dental anesthesia and pain medicine",
    "year": 2022,
    "source": "https://pubmed.ncbi.nlm.nih.gov/35449779/",
    "sourceId": "PMID 35449779"
  },
  {
    "slug": "bpc-157",
    "compound": "BPC-157",
    "area": "Vascular signaling",
    "evidence": "preclinical",
    "model": "Isolated rat aorta and cultured endothelial cells",
    "focus": "Vascular signaling",
    "title": "Modulatory effects of BPC 157 on vasomotor tone and the activation of Src-Caveolin-1-endothelial nitric oxide synthase pathway.",
    "finding": "The experiments linked vessel relaxation to nitric-oxide-dependent endothelial signaling involving Src, caveolin-1, and eNOS.",
    "limitation": "Isolated vessels and cells do not establish cardiovascular benefit or safety in people.",
    "authors": "Hsieh MJ et al.",
    "journal": "Scientific reports",
    "year": 2020,
    "source": "https://pubmed.ncbi.nlm.nih.gov/33051481/",
    "sourceId": "PMID 33051481"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Triple-receptor discovery",
    "evidence": "human",
    "model": "Receptor assays, obese mice, and a first-in-human study",
    "focus": "Triple-receptor discovery",
    "title": "LY3437943, a novel triple glucagon, GIP, and GLP-1 receptor agonist for glycemic control and weight loss: From discovery to clinical proof of concept.",
    "finding": "The compound activated three receptor systems, improved metabolic outcomes in mice, and showed an early human pharmacokinetic profile compatible with weekly investigation.",
    "limitation": "Discovery experiments and early human exposure do not establish long-term clinical benefit or retail-product equivalence.",
    "authors": "Coskun T et al.",
    "journal": "Cell metabolism",
    "year": 2022,
    "source": "https://pubmed.ncbi.nlm.nih.gov/35985340/",
    "sourceId": "PMID 35985340"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Early diabetes trial",
    "evidence": "human",
    "model": "12-week randomized phase 1b trial in adults with type 2 diabetes",
    "focus": "Early diabetes trial",
    "title": "LY3437943, a novel triple GIP, GLP-1, and glucagon receptor agonist in people with type 2 diabetes: a phase 1b, multicentre, double-blind, placebo-controlled, randomised, multiple-ascending dose trial.",
    "finding": "The trial reported improvements in glucose and weight measures; gastrointestinal adverse events were common.",
    "limitation": "A small early-phase trial with treatment discontinuations provides limited information about uncommon harms and long-term outcomes.",
    "authors": "Urva S et al.",
    "journal": "Lancet (London, England)",
    "year": 2022,
    "source": "https://pubmed.ncbi.nlm.nih.gov/36354040/",
    "sourceId": "PMID 36354040"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Liver injury model",
    "evidence": "preclinical",
    "model": "Accelerated dietary liver-injury model in female mice",
    "focus": "Liver injury model",
    "title": "Retatrutide improves steatohepatitis in an accelerated mouse model of diet-induced steatohepatitis with a fructose binge.",
    "finding": "Treatment reduced liver injury markers, lipid accumulation, and inflammation in this experimental dietary model.",
    "limitation": "The accelerated mouse model does not establish treatment of human liver disease.",
    "authors": "Viebahn GK et al.",
    "journal": "American journal of physiology. Gastrointestinal and liver physiology",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/41056349/",
    "sourceId": "PMID 41056349"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Lipid regulation",
    "evidence": "human",
    "model": "Post hoc analyses of two phase 2 trials and cultured human hepatocytes",
    "focus": "Lipid regulation",
    "title": "Decreases in circulating ANGPTL3/8 concentrations following retatrutide treatment parallel reductions in serum lipids.",
    "finding": "Declines in ANGPTL3/8 accompanied lower triglyceride and LDL measures; cell experiments investigated a glucagon-receptor mechanism.",
    "limitation": "These are secondary analyses of existing trials, not additional independent trials. Associations and cell experiments cannot prove clinical cardiovascular benefit.",
    "authors": "Wen Y et al.",
    "journal": "Diabetes, obesity & metabolism",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40726454/",
    "sourceId": "PMID 40726454",
    "studyType": "secondary-analysis"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Participant experiences",
    "evidence": "human",
    "model": "Exit interviews with 40 participants from a phase 2 obesity trial",
    "focus": "Participant experiences",
    "title": "Perceived benefits of treatment for obesity with retatrutide: A qualitative study of patients in a phase 2 clinical trial.",
    "finding": "Interviewees described changes in eating behavior and wellbeing, along with adverse effects and practical or social difficulties.",
    "limitation": "Qualitative interviews from a selected trial subset are not a separate efficacy trial or an unbiased estimate of how often experiences occur.",
    "authors": "Goetz IA et al.",
    "journal": "Obesity pillars",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/41216380/",
    "sourceId": "PMID 41216380",
    "studyType": "secondary-analysis"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Tumor and metabolic models",
    "evidence": "preclinical",
    "model": "Obese mice with experimental pancreatic or lung tumors",
    "focus": "Tumor and metabolic models",
    "title": "Incretin triple agonist retatrutide (LY3437943) alleviates obesity-associated cancer progression.",
    "finding": "Researchers reported reduced tumor engraftment or growth alongside changes in immune and metabolic measures.",
    "limitation": "Mouse tumor experiments do not establish cancer prevention or treatment in people.",
    "authors": "Marathe SJ et al.",
    "journal": "npj metabolic health and disease",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40094000/",
    "sourceId": "PMID 40094000"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Appetite questionnaires",
    "evidence": "human",
    "model": "Secondary analysis of a phase 2 diabetes trial",
    "focus": "Appetite questionnaires",
    "title": "Appetite, eating attitudes, and eating behaviours during treatment with retatrutide in adults with type 2 diabetes: Results of a phase 2 study.",
    "finding": "Higher treatment groups reported reduced hunger and disinhibited eating; changes were associated with weight reduction.",
    "limitation": "Self-reported secondary endpoints come from an existing trial and do not independently establish the mechanism of weight loss.",
    "authors": "Kanu C et al.",
    "journal": "Diabetes, obesity & metabolism",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40916752/",
    "sourceId": "PMID 40916752",
    "studyType": "secondary-analysis"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Cardiac receptor signaling",
    "evidence": "preclinical",
    "model": "Isolated mouse atrial preparations",
    "focus": "Cardiac receptor signaling",
    "title": "Contractile effects of retatrutide in isolated mouse atrial preparations.",
    "finding": "Retatrutide increased right-atrial beating rate through glucagon-receptor and cAMP-related signaling without increasing left-atrial force in the tested preparations.",
    "limitation": "Isolated mouse heart tissue cannot establish human rhythm risk or cardiovascular safety.",
    "authors": "Neumann J et al.",
    "journal": "Naunyn-Schmiedeberg's archives of pharmacology",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40464942/",
    "sourceId": "PMID 40464942"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Kidney-related measures",
    "evidence": "human",
    "model": "Post hoc analyses of two phase 2 trials",
    "focus": "Kidney-related measures",
    "title": "The Effect of Retatrutide on Kidney Parameters in Participants With Type 2 Diabetes Mellitus and/or Obesity.",
    "finding": "Higher treatment groups had lower urine albumin-to-creatinine ratios; estimated filtration changes differed between obesity and diabetes populations.",
    "limitation": "Most participants had normal baseline albumin excretion. These secondary analyses are not independent kidney-outcome trials.",
    "authors": "Heerspink HJL et al.",
    "journal": "Kidney international reports",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40630318/",
    "sourceId": "PMID 40630318",
    "studyType": "secondary-analysis"
  },
  {
    "slug": "retatrutide",
    "compound": "Retatrutide",
    "area": "Phase 3 diabetes trial",
    "evidence": "human",
    "model": "40-week randomized placebo-controlled trial in 537 adults",
    "focus": "Phase 3 diabetes trial",
    "title": "Efficacy and safety of retatrutide, a GIP, GLP-1, and glucagon receptor agonist, in people with type 2 diabetes and inadequate glycaemic control with diet and exercise (TRANSCEND-T2D-1): a double-blind, randomised, phase 3 trial.",
    "finding": "Retatrutide groups had greater reductions in HbA1c and body weight than placebo. Gastrointestinal events were the most frequent adverse events, and some participants stopped treatment because of adverse events.",
    "limitation": "This trial studied a controlled investigational formulation and selected adults with type 2 diabetes. It does not establish every long-term outcome or the identity and safety of retail research products.",
    "authors": "Bajaj HS et al.",
    "journal": "Lancet (London, England)",
    "year": 2026,
    "source": "https://pubmed.ncbi.nlm.nih.gov/42250575/",
    "sourceId": "PMID 42250575"
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Ischemic vessel formation",
    "evidence": "preclinical",
    "model": "Thymosin beta4 gene delivery in endothelial cells, mice, and rabbits",
    "focus": "Ischemic vessel formation",
    "title": "Thymosin-β4-mediated therapeutic neovascularization: role of the PI3K/AKT pathway.",
    "finding": "Thymosin beta4-induced vessel formation and limb perfusion depended on PI3K/AKT and Rho signaling in these experiments.",
    "limitation": "Gene delivery of full-length thymosin beta4 is not administration of a TB-500 retail vial; animal ischemia results do not establish human benefit.",
    "authors": "Trenkwalder T et al.",
    "journal": "Expert opinion on biological therapy",
    "year": 2015,
    "source": "https://pubmed.ncbi.nlm.nih.gov/25652683/",
    "sourceId": "PMID 25652683",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Endothelial migration",
    "evidence": "preclinical",
    "model": "Cultured endothelial progenitor cells treated with thymosin beta4",
    "focus": "Endothelial migration",
    "title": "Thymosin beta4 induces endothelial progenitor cell migration via PI3K/Akt/eNOS signal transduction pathway.",
    "finding": "Directional migration increased alongside Akt and eNOS signaling; pathway inhibitors blocked the migration response.",
    "limitation": "A cell-migration assay with thymosin beta4 does not establish vascular repair in people or equivalence to TB-500.",
    "authors": "Qiu FY et al.",
    "journal": "Journal of cardiovascular pharmacology",
    "year": 2009,
    "source": "https://pubmed.ncbi.nlm.nih.gov/19247195/",
    "sourceId": "PMID 19247195",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Cardiac injury",
    "evidence": "preclinical",
    "model": "Myocardial infarction in mice treated with thymosin beta4",
    "focus": "Cardiac injury",
    "title": "Thymosin-β4 prevents cardiac rupture and improves cardiac function in mice with myocardial infarction.",
    "finding": "Treated mice had fewer cardiac ruptures and improved measures of remodeling and cardiac function.",
    "limitation": "An induced mouse infarction and full-length thymosin beta4 do not establish human cardiac treatment or TB-500 efficacy.",
    "authors": "Peng H et al.",
    "journal": "American journal of physiology. Heart and circulatory physiology",
    "year": 2014,
    "source": "https://pubmed.ncbi.nlm.nih.gov/25015963/",
    "sourceId": "PMID 25015963",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Hair follicle biology",
    "evidence": "preclinical",
    "model": "Rat and mouse hair models and follicular keratinocytes",
    "focus": "Hair follicle biology",
    "title": "Thymosin beta4 increases hair growth by activation of hair follicle stem cells.",
    "finding": "Thymosin beta4 increased hair growth in rodents and promoted migration and differentiation of follicular cells.",
    "limitation": "Rodent hair growth and isolated cells are not human hair-loss trials; the paper studies thymosin beta4, not a verified TB-500 formulation.",
    "authors": "Philp D et al.",
    "journal": "FASEB journal : official publication of the Federation of American Societies for Experimental Biology",
    "year": 2004,
    "source": "https://pubmed.ncbi.nlm.nih.gov/14657002/",
    "sourceId": "PMID 14657002",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Traumatic brain injury",
    "evidence": "preclinical",
    "model": "Controlled cortical impact in rats treated with thymosin beta4",
    "focus": "Traumatic brain injury",
    "title": "Treatment of traumatic brain injury with thymosin β₄ in rats.",
    "finding": "Delayed treatment improved several histological and functional outcomes, but did not reduce lesion volume.",
    "limitation": "Experimental rat brain injury cannot establish recovery in people, and this is related thymosin beta4 evidence.",
    "authors": "Xiong Y et al.",
    "journal": "Journal of neurosurgery",
    "year": 2011,
    "source": "https://pubmed.ncbi.nlm.nih.gov/20486893/",
    "sourceId": "PMID 20486893",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Fracture repair",
    "evidence": "preclinical",
    "model": "Fibular osteotomy in mice treated with thymosin beta4",
    "focus": "Fracture repair",
    "title": "Thymosin β4 administration enhances fracture healing in mice.",
    "finding": "Treated calluses had improved mechanical properties and more newly mineralized tissue at measured time points.",
    "limitation": "Mouse fracture measurements do not establish clinical bone healing or equivalence between thymosin beta4 and TB-500.",
    "authors": "Brady RD et al.",
    "journal": "Journal of orthopaedic research : official publication of the Orthopaedic Research Society",
    "year": 2014,
    "source": "https://pubmed.ncbi.nlm.nih.gov/25042765/",
    "sourceId": "PMID 25042765",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Stroke in older animals",
    "evidence": "preclinical",
    "model": "Embolic stroke in aged rats treated with thymosin beta4",
    "focus": "Stroke in older animals",
    "title": "Thymosin β4 for the treatment of acute stroke in aged rats.",
    "finding": "Infarct volume was reduced, but functional outcomes, myelination, and gliosis did not improve versus control.",
    "limitation": "The negative functional result matters: reduced lesion size did not translate into measured recovery. This does not establish human stroke treatment or TB-500 efficacy.",
    "authors": "Morris DC et al.",
    "journal": "Neuroscience letters",
    "year": 2017,
    "source": "https://pubmed.ncbi.nlm.nih.gov/28864242/",
    "sourceId": "PMID 28864242",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Tumor-cell behavior",
    "evidence": "preclinical",
    "model": "Genetically manipulated mouse fibrosarcoma cells",
    "focus": "Tumor-cell behavior",
    "title": "Thymosin-beta4 regulates motility and metastasis of malignant mouse fibrosarcoma cells.",
    "finding": "Increasing thymosin beta4 expression promoted tumor formation and lung metastases; reducing expression diminished these outcomes.",
    "limitation": "A tumor-cell gene-expression experiment does not quantify cancer risk from administering TB-500, but demonstrates context-dependent biology rather than uniformly beneficial effects.",
    "authors": "Kobayashi T et al.",
    "journal": "The American journal of pathology",
    "year": 2002,
    "source": "https://pubmed.ncbi.nlm.nih.gov/11891186/",
    "sourceId": "PMID 11891186",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Corneal cell migration",
    "evidence": "preclinical",
    "model": "Cultured human corneal epithelial cells treated with thymosin beta4",
    "focus": "Corneal cell migration",
    "title": "Purinergic Signaling Involvement in Thymosin β4-mediated Corneal Epithelial Cell Migration.",
    "finding": "Migration and proliferation were associated with extracellular ATP, P2X7-related calcium signaling, and ERK phosphorylation.",
    "limitation": "Human-derived cells are not human treatment trials; this study does not establish a TB-500 eye treatment.",
    "authors": "Yang HM et al.",
    "journal": "Current eye research",
    "year": 2020,
    "source": "https://pubmed.ncbi.nlm.nih.gov/32223337/",
    "sourceId": "PMID 32223337",
    "related": true
  },
  {
    "slug": "tb-500",
    "compound": "TB-500",
    "area": "Gingival cell stress",
    "evidence": "preclinical",
    "model": "Cultured human gingival fibroblasts treated with thymosin beta4",
    "focus": "Gingival cell stress",
    "title": "Thymosin beta4 is cytoprotective in human gingival fibroblasts.",
    "finding": "The peptide reduced selected inflammatory and toxic responses, but did not protect against the tested bacterial lipopolysaccharide challenges.",
    "limitation": "Protection was stimulus-dependent in a cell culture. This is neither a human oral-health trial nor direct TB-500 evidence.",
    "authors": "Reti R et al.",
    "journal": "European journal of oral sciences",
    "year": 2008,
    "source": "https://pubmed.ncbi.nlm.nih.gov/18821984/",
    "sourceId": "PMID 18821984",
    "related": true
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Reported systemic toxicity",
    "evidence": "human",
    "model": "Single clinical case after analytically confirmed melanotan II exposure",
    "focus": "Reported systemic toxicity",
    "title": "Melanotan II injection resulting in systemic toxicity and rhabdomyolysis.",
    "finding": "The patient developed systemic toxicity including tachycardia, rhabdomyolysis, and renal dysfunction, requiring intensive care.",
    "limitation": "A single case cannot estimate the frequency of adverse events or establish a safe exposure level.",
    "authors": "Nelson ME et al.",
    "journal": "Clinical toxicology (Philadelphia, Pa.)",
    "year": 2012,
    "source": "https://pubmed.ncbi.nlm.nih.gov/23121206/",
    "sourceId": "PMID 23121206",
    "studyType": "case-report"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Melanoma case report",
    "evidence": "human",
    "model": "Single patient reporting melanotan II and sunbed use",
    "focus": "Melanoma case report",
    "title": "Melanoma associated with the use of melanotan-II.",
    "finding": "The report describes melanoma in a young woman with reported melanotan II exposure and concurrent sunbed use.",
    "limitation": "A case report with concurrent ultraviolet exposure cannot establish causation or estimate melanoma risk attributable to melanotan II.",
    "authors": "Hjuler KF et al.",
    "journal": "Dermatology (Basel, Switzerland)",
    "year": 2014,
    "source": "https://pubmed.ncbi.nlm.nih.gov/24355990/",
    "sourceId": "PMID 24355990",
    "studyType": "case-report"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Online vial characterization",
    "evidence": "preclinical",
    "model": "Chemical analysis of products from three online shops",
    "focus": "Online vial characterization",
    "title": "Identification and characterization by LC-UV-MS/MS of melanotan II skin-tanning products sold illegally on the Internet.",
    "finding": "Analyses detected melanotan II, quantities below the claimed contents, and impurities in samples from two shops.",
    "limitation": "A small historical sample does not characterize every supplier or any current batch; chemical testing is not a clinical safety study.",
    "authors": "Breindahl T et al.",
    "journal": "Drug testing and analysis",
    "year": 2015,
    "source": "https://pubmed.ncbi.nlm.nih.gov/24771717/",
    "sourceId": "PMID 24771717",
    "studyType": "laboratory"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Temperature and histamine",
    "evidence": "preclinical",
    "model": "Mouse hypothermia and mast-cell experiments",
    "focus": "Temperature and histamine",
    "title": "Melanotan II causes hypothermia in mice by activation of mast cells and stimulation of histamine 1 receptors.",
    "finding": "The hypothermic response involved mast-cell histamine and H1 signaling rather than the canonical melanocortin pathway alone.",
    "limitation": "Mouse mechanisms do not establish the frequency or severity of temperature changes in people.",
    "authors": "Jain S et al.",
    "journal": "American journal of physiology. Endocrinology and metabolism",
    "year": 2018,
    "source": "https://pubmed.ncbi.nlm.nih.gov/29812984/",
    "sourceId": "PMID 29812984"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Social behavior model",
    "evidence": "preclinical",
    "model": "Male mice in a maternal immune-activation model",
    "focus": "Social behavior model",
    "title": "Melanotan-II reverses autistic features in a maternal immune activation mouse model of autism.",
    "finding": "Melanotan II improved selected social-behavior measures in the induced model, while responses differed in comparison mice.",
    "limitation": "A mouse behavioral model does not establish treatment for human autism; weight loss and model-specific responses limit interpretation.",
    "authors": "Minakova E et al.",
    "journal": "PloS one",
    "year": 2019,
    "source": "https://pubmed.ncbi.nlm.nih.gov/30629642/",
    "sourceId": "PMID 30629642"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Oxytocin neuron activity",
    "evidence": "preclinical",
    "model": "Rat oxytocin-neuron experiments",
    "focus": "Oxytocin neuron activity",
    "title": "Effect of Melanotan-II on Brain Fos Immunoreactivity and Oxytocin Neuronal Activity and Secretion in Rats.",
    "finding": "Intravenous, but not intranasal, exposure increased neuronal firing and activation markers; somatodendritic oxytocin release did not increase.",
    "limitation": "Neuronal activation is not equivalent to hormone release or a demonstrated human behavioral benefit.",
    "authors": "Paiva L et al.",
    "journal": "Journal of neuroendocrinology",
    "year": 2017,
    "source": "https://pubmed.ncbi.nlm.nih.gov/28009464/",
    "sourceId": "PMID 28009464"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Hormone-dependent behavior",
    "evidence": "preclinical",
    "model": "Ovariectomized female rats under different hormone conditions",
    "focus": "Hormone-dependent behavior",
    "title": "The melanocortin agonist, melanotan II, enhances proceptive sexual behaviors in the female rat.",
    "finding": "Sexual solicitation increased with estradiol plus progesterone, but other behavioral measures and estradiol-only conditions did not show the same response.",
    "limitation": "Effects depended on the experimental hormonal setting and cannot establish human sexual-function treatment.",
    "authors": "Rössler AS et al.",
    "journal": "Pharmacology, biochemistry, and behavior",
    "year": 2006,
    "source": "https://pubmed.ncbi.nlm.nih.gov/17113634/",
    "sourceId": "PMID 17113634"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Cold-response physiology",
    "evidence": "preclinical",
    "model": "Cold-acclimated PACAP-deficient female mice",
    "focus": "Cold-response physiology",
    "title": "Melanotan II, a melanocortin agonist, partially rescues the impaired thermogenic capacity of pituitary adenylate cyclase-activating polypeptide deficient mice.",
    "finding": "Melanotan II partly restored thermogenic responses and altered adipose lipid use in the deficient mice.",
    "limitation": "A genetically deficient mouse model does not establish metabolic effects or safety in the general human population.",
    "authors": "McMillan TR et al.",
    "journal": "Experimental physiology",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/33332767/",
    "sourceId": "PMID 33332767"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Diet and behavior",
    "evidence": "preclinical",
    "model": "High-fat-diet zebrafish model",
    "focus": "Diet and behavior",
    "title": "Melanotan-II reverses memory impairment induced by a short-term HF diet.",
    "finding": "Treatment reversed selected diet-associated behavioral and memory impairments in zebrafish.",
    "limitation": "Fish behavioral results do not establish cognitive or metabolic treatment in people.",
    "authors": "Wekwejt P et al.",
    "journal": "Biomedicine & pharmacotherapy = Biomedecine & pharmacotherapie",
    "year": 2023,
    "source": "https://pubmed.ncbi.nlm.nih.gov/37478579/",
    "sourceId": "PMID 37478579"
  },
  {
    "slug": "mt-2",
    "compound": "MT-2",
    "area": "Food reward signaling",
    "evidence": "preclinical",
    "model": "Local nucleus accumbens administration in mice",
    "focus": "Food reward signaling",
    "title": "Melanocortin receptor agonist melanotan-II microinjected in the nucleus accumbens decreases appetitive and consumptive responding for food.",
    "finding": "Melanotan II reduced food motivation and consumption without the measured aversive response or metabolic changes.",
    "limitation": "Local brain administration in mice is not equivalent to peripheral exposure or a clinical weight-management trial.",
    "authors": "Eliason NL et al.",
    "journal": "Neuropeptides",
    "year": 2022,
    "source": "https://pubmed.ncbi.nlm.nih.gov/36155088/",
    "sourceId": "PMID 36155088"
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Muscle atrophy signaling",
    "evidence": "preclinical",
    "model": "Human plasma observations, mouse muscle, and cultured myotubes",
    "focus": "Muscle atrophy signaling",
    "title": "MOTS-c reduces myostatin and muscle atrophy signaling.",
    "finding": "Circulating MOTS-c was inversely associated with myostatin; experimental work linked muscle effects to CK2, PTEN, AKT, and FOXO1 signaling.",
    "limitation": "The human component was observational. Experimental administration in mice and cells does not establish prevention of muscle loss in people.",
    "authors": "Kumagai H et al.",
    "journal": "American journal of physiology. Endocrinology and metabolism",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/33554779/",
    "sourceId": "PMID 33554779",
    "humanObservation": true
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Autoimmune islet models",
    "evidence": "preclinical",
    "model": "NOD mice, human type 1 diabetes observations, and T-cell assays",
    "focus": "Autoimmune islet models",
    "title": "Mitochondrial-encoded MOTS-c prevents pancreatic islet destruction in autoimmune diabetes.",
    "finding": "The study reported islet protection in mice, lower endogenous MOTS-c in people with type 1 diabetes, and altered T-cell activation in experimental assays.",
    "limitation": "People were not treated with MOTS-c in a clinical trial. Observations and ex vivo assays do not establish a diabetes therapy.",
    "authors": "Kong BS et al.",
    "journal": "Cell reports",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/34320351/",
    "sourceId": "PMID 34320351",
    "humanObservation": true
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "CK2 binding and muscle",
    "evidence": "preclinical",
    "model": "Biochemical assays, mouse muscle, and human genetic observations",
    "focus": "CK2 binding and muscle",
    "title": "MOTS-c modulates skeletal muscle function by directly binding and activating CK2.",
    "finding": "Experiments identified CK2 binding and linked MOTS-c signaling to muscle preservation and glucose uptake; genetic associations varied with sex and age.",
    "limitation": "Human genetic associations are not treatment results. Mouse and biochemical findings cannot establish clinical efficacy or safety.",
    "authors": "Kumagai H et al.",
    "journal": "iScience",
    "year": 2024,
    "source": "https://pubmed.ncbi.nlm.nih.gov/39559755/",
    "sourceId": "PMID 39559755",
    "humanObservation": true
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Mitochondrial fusion",
    "evidence": "preclinical",
    "model": "Mammalian cell experiments with fusion-protein perturbation",
    "focus": "Mitochondrial fusion",
    "title": "Mitofusion is required for MOTS-c induced GLUT4 translocation.",
    "finding": "MFN2- and OPA1-related mitochondrial fusion was needed for the observed GLUT4 translocation response.",
    "limitation": "Cellular glucose-transport mechanisms do not establish improved blood glucose or clinical outcomes in people.",
    "authors": "Bhullar KS et al.",
    "journal": "Scientific reports",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/34253808/",
    "sourceId": "PMID 34253808"
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Bone-loss model",
    "evidence": "preclinical",
    "model": "Ovariectomized mice and osteoclast experiments",
    "focus": "Bone-loss model",
    "title": "Mitochondria related peptide MOTS-c suppresses ovariectomy-induced bone loss via AMPK activation.",
    "finding": "Treatment reduced bone loss and affected AMPK-related osteoclast differentiation in the model.",
    "limitation": "An induced mouse model does not establish prevention or treatment of human osteoporosis.",
    "authors": "Ming W et al.",
    "journal": "Biochemical and biophysical research communications",
    "year": 2016,
    "source": "https://pubmed.ncbi.nlm.nih.gov/27237975/",
    "sourceId": "PMID 27237975"
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Immobilization and muscle",
    "evidence": "preclinical",
    "model": "Eight-day immobilization model in male mice",
    "focus": "Immobilization and muscle",
    "title": "Mitochondrial-derived microprotein MOTS-c attenuates immobilization-induced skeletal muscle atrophy by suppressing lipid infiltration.",
    "finding": "Treatment reduced measured muscle atrophy, fat accumulation, and inflammation, with changes in AKT/FOXO signaling.",
    "limitation": "Short-term experimental immobilization does not establish human rehabilitation outcomes or long-term safety.",
    "authors": "Kumagai H et al.",
    "journal": "American journal of physiology. Endocrinology and metabolism",
    "year": 2024,
    "source": "https://pubmed.ncbi.nlm.nih.gov/38170165/",
    "sourceId": "PMID 38170165"
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Adipose metabolism",
    "evidence": "preclinical",
    "model": "Ovariectomized mice",
    "focus": "Adipose metabolism",
    "title": "MOTS-c peptide regulates adipose homeostasis to prevent ovariectomy-induced metabolic dysfunction.",
    "finding": "The study reported changes in adipose AMPK signaling, fat accumulation, insulin-related measures, and brown-fat responses.",
    "limitation": "This is an animal model, not a trial of MOTS-c in postmenopausal people.",
    "authors": "Lu H et al.",
    "journal": "Journal of molecular medicine (Berlin, Germany)",
    "year": 2019,
    "source": "https://pubmed.ncbi.nlm.nih.gov/30725119/",
    "sourceId": "PMID 30725119"
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Vascular observations",
    "evidence": "preclinical",
    "model": "Angina patient observations and rodent aortic-ring assays",
    "focus": "Vascular observations",
    "title": "Downregulation of circulating MOTS-c levels in patients with coronary endothelial dysfunction.",
    "finding": "Lower endogenous MOTS-c was associated with endothelial dysfunction in the clinical sample; experimental vessel responses improved in rodent preparations.",
    "limitation": "Endogenous levels and isolated-vessel assays do not establish that administering MOTS-c improves human vascular disease.",
    "authors": "Qin Q et al.",
    "journal": "International journal of cardiology",
    "year": 2018,
    "source": "https://pubmed.ncbi.nlm.nih.gov/29242099/",
    "sourceId": "PMID 29242099",
    "humanObservation": true
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Mitochondrial genetic variation",
    "evidence": "preclinical",
    "model": "Human genetic cohorts and mouse variant experiments",
    "focus": "Mitochondrial genetic variation",
    "title": "A pro-diabetogenic mtDNA polymorphism in the mitochondrial-derived peptide, MOTS-c.",
    "finding": "The K14Q variant was associated with type 2 diabetes in selected male and activity-defined groups; experimental work found altered peptide function.",
    "limitation": "Genetic associations can depend on population, sex, and behavior and are not evidence from a human administration trial.",
    "authors": "Zempo H et al.",
    "journal": "Aging",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/33468709/",
    "sourceId": "PMID 33468709",
    "humanObservation": true
  },
  {
    "slug": "mots-c",
    "compound": "MOTS-c",
    "area": "Exercise physiology",
    "evidence": "human",
    "model": "Human endurance, resistance, and control exercise groups",
    "focus": "Exercise physiology",
    "title": "Acute endurance exercise stimulates circulating levels of mitochondrial-derived peptides in humans.",
    "finding": "Muscle and blood mitochondrial-peptide responses were measured after exercise; the reported human MOTS-c increase was a trend rather than a statistically significant result.",
    "limitation": "Participants were not given MOTS-c. An exercise-associated trend does not establish an effect of supplemental peptide.",
    "authors": "von Walden F et al.",
    "journal": "Journal of applied physiology (Bethesda, Md. : 1985)",
    "year": 2021,
    "source": "https://pubmed.ncbi.nlm.nih.gov/34351816/",
    "sourceId": "PMID 34351816",
    "studyType": "observational"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Hypoxia and neuronal stress",
    "evidence": "preclinical",
    "model": "Experimental hypoxia and neuronal stress models",
    "focus": "Hypoxia and neuronal stress",
    "title": "[Investigation of antihypoxic properties of short peptides].",
    "finding": "Pinealon showed protective responses in the tested models, with proposed antioxidant-enzyme and excitotoxicity-related mechanisms.",
    "limitation": "Experimental stress protection does not establish human cognitive improvement or clinical neuroprotection.",
    "authors": "Kozina LS et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2008,
    "source": "https://pubmed.ncbi.nlm.nih.gov/18546825/",
    "sourceId": "PMID 18546825"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Small clinical biomarker report",
    "evidence": "human",
    "model": "Patients with chronic polymorbidity in remission",
    "focus": "Small clinical biomarker report",
    "title": "[EFFECT OF SYNTHETIC PEPTIDES ON AGING OF PATIENTS WITH CHRONIC POLYMORBIDITY AND ORGANIC BRAIN SYNDROME OF THE CENTRAL NERVOUS SYSTEM IN REMISSION].",
    "finding": "The report described changes in biological-age and nervous-system markers, alongside pro-oxidant activity and a decline in measured CD34-positive cells.",
    "limitation": "Small clinical biomarker reports do not establish rejuvenation or genetic safety. The reported marker changes include potentially unfavorable findings.",
    "authors": "Meshchaninov VN et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2015,
    "source": "https://pubmed.ncbi.nlm.nih.gov/26390612/",
    "sourceId": "PMID 26390612",
    "studyType": "observational"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Worker adaptation measures",
    "evidence": "human",
    "model": "Clinical report in locomotive workers",
    "focus": "Worker adaptation measures",
    "title": "[Analysis of some parameters of biological age and adaptation possibilities of workers of locomotive brigades].",
    "finding": "A short-course report described improvements in biological-age and adaptation indicators.",
    "limitation": "The abstract does not provide enough control or follow-up information to establish delayed aging or durable health benefits.",
    "authors": "Nazimko VA et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2012,
    "source": "https://pubmed.ncbi.nlm.nih.gov/22708445/",
    "sourceId": "PMID 22708445",
    "studyType": "observational"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Combined peptide report",
    "evidence": "human",
    "model": "Comparison of geroprotection techniques in 110 people",
    "focus": "Combined peptide report",
    "title": "[Comparative analysis of different methods of geroprotective].",
    "finding": "Combined Pinealon and Vesugen was associated with changes in the study's biological-age indicators.",
    "limitation": "A combined regimen cannot isolate Pinealon's effect; surrogate indicators are not demonstrated extension of lifespan or healthy lifespan.",
    "authors": "Myakotnykh VS et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2016,
    "source": "https://pubmed.ncbi.nlm.nih.gov/28539017/",
    "sourceId": "PMID 28539017",
    "studyType": "observational"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Age and hypoxia models",
    "evidence": "preclinical",
    "model": "Older rats exposed to hypobaria and hypothermia",
    "focus": "Age and hypoxia models",
    "title": "[Pinealon and Cortexin influence on behavior and neurochemical processes in 18-month aged rats within hypoxia and hypothermia].",
    "finding": "Pinealon and Cortexin altered selected neurotransmitter responses; effects on free-radical and caspase measures differed between peptides.",
    "limitation": "Results were model- and peptide-dependent. These experimental markers do not establish human neuroprotection.",
    "authors": "Mendzheritsky AM et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2015,
    "source": "https://pubmed.ncbi.nlm.nih.gov/28509493/",
    "sourceId": "PMID 28509493"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Occupational adaptation",
    "evidence": "human",
    "model": "Worker screening and a combined Pinealon/Vesugen report",
    "focus": "Occupational adaptation",
    "title": "[The peptide correction of neurotic disorders among professional truck-drivers].",
    "finding": "The report described better psychoemotional and adaptive indices after a combined peptide program.",
    "limitation": "The screened population is not necessarily the intervention sample. Combined treatment and limited methodological detail prevent attribution to Pinealon alone.",
    "authors": "Bashkireva AS et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2012,
    "source": "https://pubmed.ncbi.nlm.nih.gov/23734521/",
    "sourceId": "PMID 23734521",
    "studyType": "observational"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Hypoxia-related markers",
    "evidence": "preclinical",
    "model": "Acute hypoxia in older rats",
    "focus": "Hypoxia-related markers",
    "title": "[Regulation of content of cytokines in blood serum and of caspase-3 activity in brains of old rats in model of sharp hypoxic hypoxia with Cortexin and Pinealon].",
    "finding": "Treatment altered cytokine and caspase-related measures that the authors discussed in relation to neurogenesis.",
    "limitation": "Marker changes do not directly demonstrate formation of new functional neurons or clinical cognitive benefit.",
    "authors": "Mendzheritskiĭ AM et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2014,
    "source": "https://pubmed.ncbi.nlm.nih.gov/25051764/",
    "sourceId": "PMID 25051764"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Learning in aged animals",
    "evidence": "preclinical",
    "model": "Young and older rats in a Morris water maze",
    "focus": "Learning in aged animals",
    "title": "[Effect of peptide geroprotectors on the navigation system learning and caspase-3 in brain structures in rats of different age].",
    "finding": "Researchers reported improved learning measures and region-specific caspase changes after peptide exposure.",
    "limitation": "Maze performance in rats does not establish treatment of human cognitive impairment.",
    "authors": "Mendzheritski AM et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2013,
    "source": "https://pubmed.ncbi.nlm.nih.gov/28976148/",
    "sourceId": "PMID 28976148"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Oxidative-stress assays",
    "evidence": "preclinical",
    "model": "Human lipoproteins, red blood cells, and neuronal cultures in vitro",
    "focus": "Oxidative-stress assays",
    "title": "[Biological activity of regulatory peptides in model experiments in vitro].",
    "finding": "The tested peptides lacked direct antioxidant action but changed oxidation or membrane measures; baseline reactive oxygen species also increased.",
    "limitation": "Different laboratory endpoints moved in different directions. These assays do not establish a uniformly antioxidant effect or a clinical benefit.",
    "authors": "Kozina LS et al.",
    "journal": "Advances in gerontology = Uspekhi gerontologii",
    "year": 2008,
    "source": "https://pubmed.ncbi.nlm.nih.gov/18546826/",
    "sourceId": "PMID 18546826"
  },
  {
    "slug": "pinealon",
    "compound": "Pinealon",
    "area": "Peptide and DNA interactions",
    "evidence": "preclinical",
    "model": "Fluorescently labeled peptides in HeLa cells and DNA assays",
    "focus": "Peptide and DNA interactions",
    "title": "Penetration of short fluorescence-labeled peptides into the nucleus in HeLa cells and in vitro specific interaction of the peptides with deoxyribooligonucleotides and DNA.",
    "finding": "Labeled Pinealon and other short peptides entered cells and nuclei; oligonucleotide assays indicated sequence-dependent interactions.",
    "limitation": "Fluorescently labeled peptides and a cancer-cell line do not establish human gene regulation, therapeutic epigenetic effects, or safety.",
    "authors": "Fedoreyeva LI et al.",
    "journal": "Biochemistry. Biokhimiia",
    "year": 2011,
    "source": "https://pubmed.ncbi.nlm.nih.gov/22117547/",
    "sourceId": "PMID 22117547"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Transgenic tumor model",
    "evidence": "preclinical",
    "model": "Female HER-2/neu transgenic mice",
    "focus": "Transgenic tumor model",
    "title": "Epithalon decelerates aging and suppresses development of breast adenocarcinomas in transgenic her-2/neu mice.",
    "finding": "Epithalon-treated mice had longer measured lifetimes and fewer or later mammary tumors and metastases in this model.",
    "limitation": "A tumor-prone transgenic mouse model does not establish human longevity or cancer prevention.",
    "authors": "Anisimov VN et al.",
    "journal": "Bulletin of experimental biology and medicine",
    "year": 2002,
    "source": "https://pubmed.ncbi.nlm.nih.gov/12459848/",
    "sourceId": "PMID 12459848"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Colon carcinogenesis",
    "evidence": "preclinical",
    "model": "Chemically induced colon tumors in rats",
    "focus": "Colon carcinogenesis",
    "title": "Epitalon and colon carcinogenesis in rats: proliferative activity and apoptosis in colon tumors and mucosa.",
    "finding": "Continuous treatment reduced tumor-cell mitotic activity and increased apoptosis, with effects depending on treatment timing.",
    "limitation": "A carcinogen-induced rat model does not establish human cancer prevention or treatment.",
    "authors": "Kossoy G et al.",
    "journal": "International journal of molecular medicine",
    "year": 2003,
    "source": "https://pubmed.ncbi.nlm.nih.gov/12964022/",
    "sourceId": "PMID 12964022"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Light regimen and lifespan",
    "evidence": "preclinical",
    "model": "Female rats under standard, natural, or constant illumination",
    "focus": "Light regimen and lifespan",
    "title": "Effect of Ala-Glu-Asp-Gly peptide on life span and development of spontaneous tumors in female rats exposed to different illumination regimes.",
    "finding": "Lifespan and tumor responses differed by lighting regimen; lifespan did not change under the standard day/night condition.",
    "limitation": "Benefits were conditional on the model and lighting environment, rather than a general demonstration of lifespan extension.",
    "authors": "Vinogradova IA et al.",
    "journal": "Bulletin of experimental biology and medicine",
    "year": 2007,
    "source": "https://pubmed.ncbi.nlm.nih.gov/18856211/",
    "sourceId": "PMID 18856211"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Pineal-cell signaling",
    "evidence": "preclinical",
    "model": "Cultured rat pinealocytes",
    "focus": "Pineal-cell signaling",
    "title": "Molecular cellular mechanisms of peptide regulation of melatonin synthesis in pinealocyte culture.",
    "finding": "Epithalone increased melatonin in the culture medium and markers involved in its synthesis; norepinephrine altered the response.",
    "limitation": "Cultured pineal cells do not establish improved sleep or circadian outcomes in people.",
    "authors": "Khavinson VKh et al.",
    "journal": "Bulletin of experimental biology and medicine",
    "year": 2012,
    "source": "https://pubmed.ncbi.nlm.nih.gov/22816096/",
    "sourceId": "PMID 22816096"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Retinal wound model",
    "evidence": "preclinical",
    "model": "High-glucose-injured human retinal epithelial cells",
    "focus": "Retinal wound model",
    "title": "The Antioxidant Tetrapeptide Epitalon Enhances Delayed Wound Healing in an in Vitro Model of Diabetic Retinopathy.",
    "finding": "Epitalon improved scratch-wound closure and reduced selected oxidative-stress, transition, and fibrosis-related responses in the cell model.",
    "limitation": "Human-derived cells are not a clinical retinopathy trial; ocular delivery, efficacy, and safety remain unestablished by this experiment.",
    "authors": "Gatta M et al.",
    "journal": "Stem cell reviews and reports",
    "year": 2025,
    "source": "https://pubmed.ncbi.nlm.nih.gov/40493162/",
    "sourceId": "PMID 40493162"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Cellular division limits",
    "evidence": "preclinical",
    "model": "Cultured human fetal pulmonary fibroblasts",
    "focus": "Cellular division limits",
    "title": "Peptide promotes overcoming of the division limit in human somatic cell.",
    "finding": "Treated aging fibroblasts had longer measured telomeres and continued dividing beyond the untreated comparison cultures.",
    "limitation": "Extending cell division in culture does not establish healthy aging, longer human lifespan, or clinical safety.",
    "authors": "Khavinson VKh et al.",
    "journal": "Bulletin of experimental biology and medicine",
    "year": 2004,
    "source": "https://pubmed.ncbi.nlm.nih.gov/15455129/",
    "sourceId": "PMID 15455129"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Primate hormone rhythms",
    "evidence": "preclinical",
    "model": "Female rhesus monkeys of different ages",
    "focus": "Primate hormone rhythms",
    "title": "Synthetic tetrapeptide epitalon restores disturbed neuroendocrine regulation in senescent monkeys.",
    "finding": "The study reported increased evening melatonin and changes toward a more regular cortisol secretion rhythm in older monkeys.",
    "limitation": "A nonhuman primate hormone study does not establish human sleep improvement or longevity.",
    "authors": "Khavinson V et al.",
    "journal": "Neuro endocrinology letters",
    "year": 2001,
    "source": "https://pubmed.ncbi.nlm.nih.gov/11524632/",
    "sourceId": "PMID 11524632"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Stress and immune signaling",
    "evidence": "preclinical",
    "model": "Stressed mice, thymocyte assays, and cerebral membrane preparations",
    "focus": "Stress and immune signaling",
    "title": "Effect of epitalon on interleukin-1beta signal transduction and the reaction of thymocyte blast transformation under stress.",
    "finding": "Epitalon altered thymocyte proliferation and interleukin-1beta-related sphingomyelin signaling in the tested stress conditions.",
    "limitation": "Experimental immune signaling is not evidence of a safe or beneficial immune treatment in people.",
    "authors": "Khavinson VKh et al.",
    "journal": "Neuro endocrinology letters",
    "year": 2002,
    "source": "https://pubmed.ncbi.nlm.nih.gov/12500162/",
    "sourceId": "PMID 12500162"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Inherited retinal degeneration",
    "evidence": "preclinical",
    "model": "Campbell rats and offspring with different exposure periods",
    "focus": "Inherited retinal degeneration",
    "title": "Retinoprotective effect of Epithalon in campbell rats of various ages.",
    "finding": "Retinal structure and functional activity were preserved longer in the tested exposure conditions, including maternal and postnatal treatment.",
    "limitation": "A particular rat retinal model and exposure schedule do not establish prevention of human eye disease.",
    "authors": "Khavinson VKh et al.",
    "journal": "Bulletin of experimental biology and medicine",
    "year": 2003,
    "source": "https://pubmed.ncbi.nlm.nih.gov/12910293/",
    "sourceId": "PMID 12910293"
  },
  {
    "slug": "epitalon",
    "compound": "Epitalon",
    "area": "Lighting and male rat aging",
    "evidence": "preclinical",
    "model": "Male rats under different illumination regimens",
    "focus": "Lighting and male rat aging",
    "title": "Geroprotective effect of ala-glu-asp-gly peptide in male rats exposed to different illumination regimens.",
    "finding": "Mean lifespan was virtually unchanged, while selected aging-rate measures and spontaneous tumor incidence differed with treatment.",
    "limitation": "The unchanged mean lifespan and lighting-dependent model limit broad longevity claims; these results are not human evidence.",
    "authors": "Vinogradova IA et al.",
    "journal": "Bulletin of experimental biology and medicine",
    "year": 2008,
    "source": "https://pubmed.ncbi.nlm.nih.gov/19110597/",
    "sourceId": "PMID 19110597"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Acute lung inflammation",
    "evidence": "preclinical",
    "model": "LPS-exposed macrophages and mice",
    "focus": "Acute lung inflammation",
    "title": "The tri-peptide GHK-Cu complex ameliorates lipopolysaccharide-induced acute lung injury in mice.",
    "finding": "GHK-Cu reduced selected inflammatory cytokines, oxidative-stress responses, and lung injury findings.",
    "limitation": "An induced mouse injury and cell assays do not establish human acute-lung-injury treatment.",
    "authors": "Park JR et al.",
    "journal": "Oncotarget",
    "year": 2016,
    "source": "https://pubmed.ncbi.nlm.nih.gov/27517151/",
    "sourceId": "PMID 27517151"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Silica-related lung injury",
    "evidence": "preclinical",
    "model": "Silicosis mouse model and macrophage cultures",
    "focus": "Silica-related lung injury",
    "title": "The glycyl-l-histidyl-l-lysine-Cu2+ tripeptide complex attenuates lung inflammation and fibrosis in silicosis by targeting peroxiredoxin 6.",
    "finding": "Treatment attenuated inflammation and fibrosis, with experiments identifying peroxiredoxin 6 as a molecular target.",
    "limitation": "Experimental silica exposure does not establish an effective or safe treatment for human silicosis.",
    "authors": "Bian Y et al.",
    "journal": "Redox biology",
    "year": 2024,
    "source": "https://pubmed.ncbi.nlm.nih.gov/38879894/",
    "sourceId": "PMID 38879894"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Smoke and skeletal muscle",
    "evidence": "preclinical",
    "model": "Human COPD observations, cultured myotubes, and smoke-exposed mice",
    "focus": "Smoke and skeletal muscle",
    "title": "Glycyl-l-histidyl-l-lysine-Cu2+ rescues cigarette smoking-induced skeletal muscle dysfunction via a sirtuin 1-dependent pathway.",
    "finding": "Patients had lower endogenous GHK levels; GHK-Cu improved selected muscle and oxidative-stress measures in cells and mice through SIRT1-related signaling.",
    "limitation": "The small human sample was observational and measured GHK, not response to GHK-Cu treatment. Experimental benefits cannot establish clinical efficacy.",
    "authors": "Deng M et al.",
    "journal": "Journal of cachexia, sarcopenia and muscle",
    "year": 2023,
    "source": "https://pubmed.ncbi.nlm.nih.gov/36905132/",
    "sourceId": "PMID 36905132",
    "humanObservation": true
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Liposomal wound delivery",
    "evidence": "preclinical",
    "model": "Endothelial cell cultures and scald wounds in mice",
    "focus": "Liposomal wound delivery",
    "title": "GHK-Cu-liposomes accelerate scald wound healing in mice by promoting cell proliferation and angiogenesis.",
    "finding": "Liposomal GHK-Cu promoted cell proliferation and angiogenesis and shortened healing time in the tested mouse wounds.",
    "limitation": "A specific liposomal formulation and animal burns do not establish equivalent effects from other products or human wound care.",
    "authors": "Wang X et al.",
    "journal": "Wound repair and regeneration : official publication of the Wound Healing Society [and] the European Tissue Repair Society",
    "year": 2017,
    "source": "https://pubmed.ncbi.nlm.nih.gov/28370978/",
    "sourceId": "PMID 28370978"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Pulmonary fibrosis model",
    "evidence": "preclinical",
    "model": "Bleomycin-induced lung injury in mice",
    "focus": "Pulmonary fibrosis model",
    "title": "Protective effects of GHK-Cu in bleomycin-induced pulmonary fibrosis via anti-oxidative stress and anti-inflammation pathways.",
    "finding": "Treatment reduced inflammatory and fibrotic changes and altered Nrf2, NF-kappaB, and TGF-beta/Smad-related responses.",
    "limitation": "Chemically induced mouse fibrosis does not establish treatment of human idiopathic pulmonary fibrosis.",
    "authors": "Ma WH et al.",
    "journal": "Life sciences",
    "year": 2020,
    "source": "https://pubmed.ncbi.nlm.nih.gov/31809714/",
    "sourceId": "PMID 31809714"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Matrix remodeling",
    "evidence": "preclinical",
    "model": "Cultured dermal fibroblasts",
    "focus": "Matrix remodeling",
    "title": "The tripeptide-copper complex glycyl-L-histidyl-L-lysine-Cu2+ stimulates matrix metalloproteinase-2 expression by fibroblast cultures.",
    "finding": "GHK-Cu increased MMP-2 and tissue-inhibitor secretion; copper ions reproduced the MMP-2 response, while GHK alone did not.",
    "limitation": "Cell-culture remodeling markers do not establish improved clinical wounds or cosmetic outcomes, and the copper contribution matters.",
    "authors": "Simeon A et al.",
    "journal": "Life sciences",
    "year": 2000,
    "source": "https://pubmed.ncbi.nlm.nih.gov/11045606/",
    "sourceId": "PMID 11045606"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Skin delivery experiments",
    "evidence": "preclinical",
    "model": "In vitro skin models, including excised human skin",
    "focus": "Skin delivery experiments",
    "title": "Microneedle-Mediated Delivery of Copper Peptide Through Skin.",
    "finding": "Microneedle pretreatment increased measured GHK-Cu passage through skin compared with intact skin in the laboratory assays.",
    "limitation": "Excised skin and experimental delivery devices are not a human treatment trial or proof that a topical product has the same absorption.",
    "authors": "Li H et al.",
    "journal": "Pharmaceutical research",
    "year": 2015,
    "source": "https://pubmed.ncbi.nlm.nih.gov/25690343/",
    "sourceId": "PMID 25690343",
    "studyType": "laboratory"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Post-laser skin trial",
    "evidence": "human",
    "model": "Randomized post-laser skin-care study with 13 completers",
    "focus": "Post-laser skin trial",
    "title": "Effects of topical copper tripeptide complex on CO2 laser-resurfaced skin.",
    "finding": "Objective evaluations found no significant between-group improvement in redness, wrinkles, or skin quality; patient satisfaction was higher in the GHK-Cu group.",
    "limitation": "The small study and discrepancy between subjective satisfaction and objective outcomes limit efficacy claims. Results concern the tested topical regimen.",
    "authors": "Miller TR et al.",
    "journal": "Archives of facial plastic surgery",
    "year": 2006,
    "source": "https://pubmed.ncbi.nlm.nih.gov/16847171/",
    "sourceId": "PMID 16847171"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Ligament graft healing",
    "evidence": "preclinical",
    "model": "ACL reconstruction in rats",
    "focus": "Ligament graft healing",
    "title": "Tripeptide-copper complex GHK-Cu (II) transiently improved healing outcome in a rat model of ACL reconstruction.",
    "finding": "Selected knee-laxity and graft-stiffness measures improved at six weeks, but benefits were not maintained at twelve weeks; several other outcomes did not differ.",
    "limitation": "Temporary, endpoint-specific effects in rats do not establish durable human ligament repair.",
    "authors": "Fu SC et al.",
    "journal": "Journal of orthopaedic research : official publication of the Orthopaedic Research Society",
    "year": 2015,
    "source": "https://pubmed.ncbi.nlm.nih.gov/25731775/",
    "sourceId": "PMID 25731775"
  },
  {
    "slug": "ghk-cu",
    "compound": "GHK-Cu",
    "area": "Smoke-induced lung changes",
    "evidence": "preclinical",
    "model": "Smoke-exposed mice and cultured human alveolar cells",
    "focus": "Smoke-induced lung changes",
    "title": "Glycyl-L-histidyl-L-lysine-Cu2+ attenuates cigarette smoke-induced pulmonary emphysema and inflammation by reducing oxidative stress pathway.",
    "finding": "GHK-Cu reduced selected emphysema, inflammatory, and oxidative-stress measures with changes in NF-kappaB and Nrf2 signaling.",
    "limitation": "Animal exposure and cultured human cells do not establish clinical COPD treatment or human safety.",
    "authors": "Zhang Q et al.",
    "journal": "Frontiers in molecular biosciences",
    "year": 2022,
    "source": "https://pubmed.ncbi.nlm.nih.gov/35936787/",
    "sourceId": "PMID 35936787"
  }
];
